server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mahmoudabbasi/spring-config-demo
          search-paths: config-repo
          clone-on-start: true

  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh,refresh,health,info"


